### ISSUE TITLE
mirrobrain-docker fails to build

### ISSUE THREAD

**Issue by rgaudin** [kiwix/maintenance#72] opened 2019-05-22 08:19 UTC
Looking at https://cloud.docker.com/u/kiwix/repository/docker/kiwix/mirrorbrain/builds it seems that all recent builds of mirrorbrain-docker failed.

Logs point to a python dependency (`cmdln`)

**Comment by florentk** [comment] 2019-05-22 10:53
@rgaudin yes I am correcting that

**Comment by florentk** [comment] 2019-05-22 12:34
In addition of cmdline, maxmind has changed many things, GeoIp C API do not compile anymore :(

**Comment by kelson42** [comment] 2019-05-22 12:41
@florentk Please report a bug to https://github.com/poeml/mirrorbrain and for the rest with should have a sticky version for these dependences (stick to an older version and don't take the most recent one)

**Comment by florentk** [comment] 2019-05-22 15:19
@kelson42 mod_mirrorbrain for apache use mod_geoip2 (2 for Apache 2). mod_geoip2 use geoip-api-c library and this is for the GeoIP Legacy format (dat). This format were discontinued on January 2, 2019 and we can not download the database with this format anymore.

Conclusion, mod_mirrorbrain should be use the news database format with mod_maxminddb. Mirrorbrain no longeur had commit since 2017 ...  I have not hope that the problem is solved

**Comment by florentk** [comment] 2019-05-22 15:22
possible solution, use the CSV format and convert to DAT format with this tool : https://github.com/mteodoro/mmutils

**Comment by florentk** [comment] 2019-05-23 00:21
instead use CSV I propose to use the old DAT format database (extract from current docker image) and put  it in a volume. After we can update this volume from the updated CSV databse with mmutils. But in futures mirrorbrain should use mod_maxminddb.

The pull request : https://github.com/kiwix/maintenance/pull/75

**Comment by kelson42** [comment] 2019-05-23 11:32
@florentk OK, I have merged the PR. The /data/geoip needs to be populated and then the Docker container updated.

**Comment by kelson42** [comment] 2019-05-23 12:06
@florentk Image is ready - successfuly built. https://cloud.docker.com/u/kiwix/repository/docker/kiwix/mirrorbrain/builds

**Closed** 2019-05-23 19:34 UTC
Labels: bug, docker
