### ISSUE TITLE
`robots.txt` has not being migrated in library image and more

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#13] opened 2018-11-03 17:02 UTC
In the original Nginx vhost:
```
  location /robots.txt {
    alias /var/www/library.kiwix.org/robots.txt;
  }
```

with `robots.txt` is

```
User-agent: *
Crawl-delay: 3
```

On the top it is also *really important* to threshold the number of request to library.kiwix.org. Our old Nginx configuration had:
```
limit_req_zone $binary_remote_addr zone=limit:10m rate=3r/s;
```
This should be migrated too

**Comment by kelson42** [comment] 2018-11-04 14:11
@florentk I reopen this ticket as the fix somehow does not work. We have currently a load>2 on the server because of the library container. The kiwix-serve daemon delivers at high speed content, which is quite a sign the throttling does not work properly.

**Comment by florentk** [comment] 2018-11-05 08:58
duplicate of #16

**Closed by florentk** 2018-11-05 08:58 UTC
Labels: bug
